In [12]:
import numpy as np
import pandas as pd
import seaborn as sns

In [13]:
covid=pd.read_csv('covid.csv')

In [14]:
covid

,age,gender,fever,cough,city,has_covid
0,20,Male,99.3,Mild,Chennai,No
1,74,Male,101.5,Mild,Chennai,No
2,26,Male,102.9,Mild,Delhi,Yes
3,73,Female,NaN,Mild,Delhi,No
4,57,Female,101.3,Strong,Chennai,Yes
...,...,...,...,...,...,...
95,40,Female,102.3,Strong,Chennai,Yes
96,46,Female,NaN,Mild,Mumbai,No
97,60,Female,98.6,Strong,Hyderabad,Yes
98,26,Female,100.6,Mild,Bangalore,Yes


In [33]:
covid['cough'].value_counts()

cough
Mild      53
Strong    47
Name: count, dtype: int64

In [15]:
covid.isnull().sum()     #  fever have 10 value null

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [16]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [17]:
from sklearn.model_selection import train_test_split

In [18]:
x_train,x_test,y_train,y_test=train_test_split(covid.drop(columns=['has_covid']),covid['has_covid'],test_size=0.3)

In [19]:
x_train

,age,gender,fever,cough,city
52,74,Male,NaN,Mild,Delhi
8,60,Female,103.0,Mild,Delhi
51,70,Female,99.5,Mild,Delhi
72,25,Female,NaN,Strong,Bangalore
30,28,Male,98.3,Mild,Mumbai
...,...,...,...,...,...
95,40,Female,102.3,Strong,Chennai
82,60,Female,100.3,Strong,Hyderabad
86,61,Male,102.5,Mild,Hyderabad
69,54,Male,98.3,Mild,Bangalore


In [29]:
# if dont use colume transformer so we do one by one like that
covid['fever'].isnull().sum()

np.int64(10)

In [23]:
# first we fill the messing value of fever colum so we used impute funtion
si=SimpleImputer()
x_train_fever=si.fit_transform(x_train[['fever']])
x_test_fever=si.fit_transform(x_test[['fever']])

In [31]:
x_train_fever      # so now there is no nul value in fever all are replace by data mean value 

array([[100.14603175],
       [103.        ],
       [ 99.5       ],
       [100.14603175],
       [ 98.3       ],
       [101.3       ],
       [ 99.3       ],
       [100.14603175],
       [ 97.        ],
       [100.8       ],
       [100.14603175],
       [ 99.5       ],
       [100.14603175],
       [101.5       ],
       [100.5       ],
       [ 97.1       ],
       [ 97.2       ],
       [102.9       ],
       [ 98.6       ],
       [102.3       ],
       [101.8       ],
       [ 99.9       ],
       [ 99.6       ],
       [101.5       ],
       [100.1       ],
       [103.9       ],
       [ 99.        ],
       [103.        ],
       [ 99.8       ],
       [101.1       ],
       [101.        ],
       [ 98.5       ],
       [ 98.6       ],
       [ 97.7       ],
       [101.1       ],
       [ 97.6       ],
       [100.14603175],
       [ 98.        ],
       [ 98.8       ],
       [100.8       ],
       [ 99.        ],
       [ 97.5       ],
       [ 97.        ],
       [100

In [32]:
# so fever coume is done
# now we see cough colume is is ordinal ctagorical data so we used ordinal sacling


In [41]:
os=OrdinalEncoder(categories=[['Mild','Strong']])
x_train_cough=os.fit_transform(x_train[['cough']])
x_test_caugh=os.fit_transform(x_test[['cough']])             

In [42]:
x_train_cough

array([[0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.]])

In [43]:
# now we done ordinal data now nominal data
ohe=OneHotEncoder(drop='first',sparse_output=False)   # we deop first from both due to muticollinarity
x_train_gen_city=ohe.fit_transform(x_train,[[' gender','city']])
x_test_gen_city=ohe.fit_transform(x_test,[[' gender','city']])  

In [44]:
x_train_gen_city

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.]], shape=(70, 89))

In [52]:
# now we want to value of age to extract them
x_train_age=x_train.drop(columns=['gender','city','fever','cough']).values
x_test_age=x_test.drop(columns=['gender','city','fever','cough']).values


In [53]:
x_train_age

array([[74],
       [60],
       [70],
       [25],
       [28],
       [57],
       [33],
       [70],
       [57],
       [64],
       [51],
       [71],
       [52],
       [74],
       [46],
       [64],
       [43],
       [53],
       [75],
       [24],
       [77],
       [27],
       [27],
       [29],
       [79],
       [33],
       [32],
       [26],
       [66],
       [26],
       [49],
       [62],
       [60],
       [63],
       [54],
       [54],
       [46],
       [28],
       [66],
       [30],
       [77],
       [80],
       [29],
       [79],
       [43],
       [20],
       [41],
       [26],
       [30],
       [63],
       [24],
       [67],
       [66],
       [47],
       [62],
       [57],
       [20],
       [80],
       [38],
       [75],
       [76],
       [32],
       [50],
       [41],
       [35],
       [40],
       [60],
       [61],
       [54],
       [73]])

In [61]:
# now combine all
x_train_comb=np.concatenate((x_train_age,x_train_fever,x_train_gen_city,x_train_cough),axis=1)
x_test_comp=np.concatenate((x_test_age,x_test_fever,x_test_gen_city,x_test_caugh),axis=1)

In [63]:
x_train_comb

array([[ 74.        , 100.14603175,   0.        , ...,   0.        ,
          0.        ,   0.        ],
       [ 60.        , 103.        ,   0.        , ...,   0.        ,
          0.        ,   0.        ],
       [ 70.        ,  99.5       ,   0.        , ...,   0.        ,
          0.        ,   0.        ],
       ...,
       [ 61.        , 102.5       ,   0.        , ...,   0.        ,
          0.        ,   0.        ],
       [ 54.        ,  98.3       ,   0.        , ...,   0.        ,
          0.        ,   0.        ],
       [ 73.        , 102.2       ,   0.        , ...,   0.        ,
          1.        ,   0.        ]], shape=(70, 92))

In [64]:
# it is so hard to do if colis 100 we do on 100 colume so 

NOW USE COLUM TRANSFORMER METHOD

In [65]:
from sklearn.compose import ColumnTransformer

In [66]:
transformer=ColumnTransformer(transformers= [
    ('tran1',SimpleImputer(),['fever']),
    ('tran2',OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),
    ('tran3',OneHotEncoder(sparse_output=False,drop='first'),['gender','city'])] ,remainder='passthrough')
#reminder hve two value 'drop','passthrough' so what we want to do 
# in this class first we make obj of each col and ofter that encoding type ,and in last col name
# the values are pass in tuple it is tuple

In [68]:
transformer.fit_transform(x_train).shape

(70, 9)

In [70]:
transformer.fit_transform(x_test).shape

(30, 8)